#!/bin/bash

function pre_install_nabu() {
    # Install OS packages if necessary with "install_package ...".
}

function install_nabu() {
    # Install the service.
    setup_develop $NABU_DIR
}

function configure_nabu() {
    # Configure the service.
    cp $NABU_DIR/etc/nabu/api-paste.ini $NABU_API_PASTE_FILE

    if is_service_enabled ceilometer-collector; then
        iniset $CEILOMETER_CONF DEFAULT event_dispatchers nabu
    fi
}

function init_nabu() {
    # Initialize and start the service.
    recreate_database nabu

    $NABU_BIN_DIR/nabu-manage upgrade
}

function start_nabu() {
    run_process nabu-api "$NABU_BIN_DIR/nabu-wsgi-api --config-file=$NABU_CONF"
}

function stop_nabu() {
    # Shut the service down.
    stop_process nabu-api
}

function create_nabu_accounts {
    create_service_user "nabu"

    local nabu_service=$(get_or_create_service "nabu" \
        "subscription" "Nabu Service")
    get_or_create_endpoint $nabu_service \
        "$REGION_NAME" \
        "$NABU_SERVICE_PROTOCOL://$NABU_SERVICE_HOST:$NABU_SERVICE_PORT" \
        "$NABU_SERVICE_PROTOCOL://$NABU_SERVICE_HOST:$NABU_SERVICE_PORT" \
        "$NABU_SERVICE_PROTOCOL://$NABU_SERVICE_HOST:$NABU_SERVICE_PORT"

}
